"""Exports: the worked solution as a PDF, the network diagram as a PNG and the
training history as CSV."""

from __future__ import annotations

import csv
from datetime import date

from PySide6.QtCore import QMarginsF, QPointF, QRectF, Qt
from PySide6.QtGui import QColor, QFont, QImage, QPageLayout, QPageSize, QPainter, QPdfWriter

from .. import APP_NAME, homework
from ..content.blocks import Block
from ..content.diagram import DiagramFrame
from ..core.network import PARAM_NAMES
from ..core.training import TrainingRun
from .document_painter import DocLayout, DocumentPainter, Placed
from .network_painter import VH, VW, NetworkPainter
from .theme import LIGHT, UI_FAMILIES, UI_FAMILY, Theme

DPI = 96                      # the PDF uses screen units, so text measures exactly as on screen
MARGIN_X = 66.0
MARGIN_TOP = 78.0
MARGIN_BOTTOM = 70.0


def paginate(layout: DocLayout, page_height: float) -> list[list[tuple[Placed, float]]]:
    """Split laid-out blocks into pages; a heading stays with the block after it."""
    pages: list[list[tuple[Placed, float]]] = [[]]
    y = 0.0
    blocks = layout.blocks
    for i, block in enumerate(blocks):
        gap = block.top - (blocks[i - 1].top + blocks[i - 1].height) if i else 0.0
        needed = block.height
        if block.keep_with_next and i + 1 < len(blocks):
            following = blocks[i + 1]
            needed = following.top + following.height - block.top
        if pages[-1] and y + gap + needed > page_height:
            pages.append([])
            y, gap = 0.0, 0.0
        pages[-1].append((block, y + gap))
        y += gap + block.height
    return pages


def _ui_font(px: float, bold: bool = False) -> QFont:
    font = QFont(UI_FAMILY)
    font.setFamilies(UI_FAMILIES)
    font.setPointSizeF(px * 0.75)
    font.setBold(bold)
    return font


def export_solution_pdf(path: str, blocks: tuple[Block, ...], title: str) -> int:
    """Write the document to ``path``; returns the number of pages."""
    writer = QPdfWriter(path)
    writer.setResolution(DPI)
    writer.setPageLayout(QPageLayout(QPageSize(QPageSize.PageSizeId.A4), QPageLayout.Orientation.Portrait,
                                     QMarginsF(0, 0, 0, 0)))
    writer.setTitle(title)
    writer.setCreator(f"{APP_NAME} — {homework.STUDENT.name}")
    page = writer.pageLayout().fullRectPixels(DPI)
    width, height = float(page.width()), float(page.height())

    figure = NetworkPainter(LIGHT)

    def paint_figure(painter: QPainter, rect: QRectF, kind: str, payload) -> None:
        if kind == "network" and payload is not None:
            figure.paint(painter, rect, payload, 1.0, mode="figure")

    document = DocumentPainter(LIGHT, "print", paint_figure)
    layout = document.layout(blocks, width - 2 * MARGIN_X)
    pages = paginate(layout, height - MARGIN_TOP - MARGIN_BOTTOM)

    painter = QPainter()
    if not painter.begin(writer):
        raise OSError(f"Could not write {path}. Is the file open in another program?")
    try:
        painter.setRenderHint(QPainter.RenderHint.Antialiasing)
        painter.setRenderHint(QPainter.RenderHint.TextAntialiasing)
        muted, rule = QColor(LIGHT.muted), QColor(LIGHT.border2)
        for number, content in enumerate(pages, start=1):
            if number > 1:
                writer.newPage()
            painter.setFont(_ui_font(10.5))
            painter.setPen(muted)
            painter.drawText(QPointF(MARGIN_X, 42), f"{homework.TITLE} · {homework.SUBTITLE}")
            right = f"{homework.STUDENT.name} · Group {homework.STUDENT.group}"
            painter.drawText(QRectF(MARGIN_X, 28, width - 2 * MARGIN_X, 20),
                             Qt.AlignmentFlag.AlignRight | Qt.AlignmentFlag.AlignVCenter, right)
            painter.fillRect(QRectF(MARGIN_X, 52, width - 2 * MARGIN_X, 0.8), rule)
            footer_y = height - 36
            painter.fillRect(QRectF(MARGIN_X, footer_y - 16, width - 2 * MARGIN_X, 0.8), rule)
            painter.setPen(muted)
            painter.drawText(QPointF(MARGIN_X, footer_y), f"Generated by {APP_NAME} on {date.today():%d %B %Y}")
            painter.drawText(QRectF(MARGIN_X, footer_y - 12, width - 2 * MARGIN_X, 16),
                             Qt.AlignmentFlag.AlignRight | Qt.AlignmentFlag.AlignVCenter,
                             f"Page {number} of {len(pages)}")
            for block, y in content:
                block.paint(painter, MARGIN_X, MARGIN_TOP + y)
    finally:
        painter.end()
    return len(pages)


def render_network(frame: DiagramFrame, theme: Theme, width: int = 2000, progress: float = 1.0,
                   background: bool = True) -> QImage:
    height = int(width * VH / VW)
    image = QImage(width, height, QImage.Format.Format_ARGB32_Premultiplied)
    image.fill(QColor(theme.surface) if background else QColor(0, 0, 0, 0))
    painter = QPainter(image)
    NetworkPainter(theme).paint(painter, QRectF(16, 16, width - 32, height - 32), frame, progress)
    painter.end()
    return image


def export_network_png(path: str, frame: DiagramFrame, theme: Theme, progress: float = 1.0) -> None:
    if not render_network(frame, theme, progress=progress).save(path, "PNG"):
        raise OSError(f"Could not write {path}.")


def export_training_csv(path: str, runs: dict[str, TrainingRun]) -> None:
    with open(path, "w", newline="", encoding="utf-8") as handle:
        writer = csv.writer(handle)
        writer.writerow(["activation", "learning_rate", "iteration", "error", "h_out", *PARAM_NAMES])
        for key, run in runs.items():
            for k, (error, h_out, params) in enumerate(zip(run.errors, run.outputs, run.params), start=1):
                writer.writerow([key, f"{run.lr:g}", k, f"{error:.12g}", f"{h_out:.12g}",
                                 *(f"{v:.12g}" for v in params.values())])
